import {test,expect,type Page} from '@playwright/test';
import {paperIntroduction} from './writing-helpers';
const evidence=(item:string,form:string,toneNumbers:string,dimensions:string)=>({id:crypto.randomUUID(),at:1,sessionId:'prior',taskId:'fixture',type:'introduction_dimensions',detail:{item,form,script:'hant',toneNumbers,dimensions,introductionVersion:1}});
async function plan(page:Page,tasks:string[],events:any[]=[]){await page.goto('/');await page.getByRole('button',{name:'Weiterlernen',exact:true}).waitFor();await page.evaluate(async({tasks,events})=>{const db=await new Promise<IDBDatabase>(r=>{const q=indexedDB.open('language-learning-local');q.onsuccess=()=>r(q.result);});await new Promise<void>(r=>{const t=db.transaction(['sessions','events'],'readwrite');t.objectStore('sessions').put({id:'intro',plannerVersion:'d1',plan:[...tasks,'closure'],index:0,completed:false,startedAt:Date.now(),updatedAt:Date.now()+100,script:'hant'});for(const e of events)t.objectStore('events').put(e);t.oncomplete=()=>r();});db.close();},{tasks,events});await page.reload();await page.getByRole('button',{name:'Weiterlernen',exact:true}).click();}
async function events(page:Page){return page.evaluate(async()=>{const db=await new Promise<IDBDatabase>(r=>{const q=indexedDB.open('language-learning-local');q.onsuccess=()=>r(q.result);});return new Promise<any[]>(r=>{const q=db.transaction('events').objectStore('events').getAll();q.onsuccess=()=>{r(q.result);db.close();};});});}
test('new Hanzi is focused and associated before a later reading attempt',async({page},info)=>{
 await page.setViewportSize({width:320,height:844});await plan(page,['d-read-qing','d-read-qing']);const intro=page.locator('.attentionIntroduction');await expect(intro).toHaveAttribute('data-focus','hanzi');await expect(page.getByRole('textbox',{name:'Deine Antwort',exact:true})).toHaveCount(0);await expect(intro.locator('.pinyin,.unitPinyin')).toHaveCount(0);await expect(intro.locator('.hanziHero')).toHaveText('請');
 await page.screenshot({path:`work/c23-intro-${info.project.name}-hanzi-320.png`,fullPage:true});
 await page.getByRole('button',{name:'Bedeutung dazunehmen',exact:true}).click();await expect(intro).toHaveAttribute('data-focus','connect');await expect(intro.locator('.pinyin')).toHaveText('qǐng');await expect(intro.locator('.meaning')).toHaveText('bitte');expect((await events(page)).filter(e=>e.type==='attempt')).toHaveLength(0);
 await page.getByRole('button',{name:'Weiter',exact:true}).click();await expect(intro).toHaveCount(0);await expect(page.locator('.pinyin,.unitPinyin')).toHaveCount(0);await expect(page.locator('.lessonCard > .eyebrow')).toContainText('Aus dem Gedächtnis');await page.getByRole('textbox',{name:'Deine Antwort',exact:true}).fill('bitte');await page.getByRole('button',{name:'Prüfen',exact:true}).click();await expect(page.locator('.feedback')).toHaveText('Richtig.');
 const log=await events(page);expect(log.filter(e=>e.type==='attempt')).toHaveLength(1);expect(log.some(e=>e.type==='introduction_dimensions'&&e.detail.dimensions.includes('hanzi'))).toBe(true);
});
test('partial introduction resumes missing focus; fully introduced items stay compact and recognition is not writing',async({page})=>{
 await plan(page,['d-meet-qing','d-meet-qing'],[evidence('qing','請','qing3','meaning,pronunciation')]);await expect(page.locator('.attentionIntroduction')).toHaveAttribute('data-focus','hanzi');await page.getByRole('button',{name:'Bedeutung dazunehmen',exact:true}).click();await page.getByRole('button',{name:'Weiter',exact:true}).click();await expect(page.locator('.attentionIntroduction')).toHaveCount(0);await expect(page.getByRole('button',{name:'Pinyin zeigen',exact:true})).toBeVisible();await expect(page.locator('.pinyin')).toHaveCount(0);
 await plan(page,['write-recall','write-recall'],[evidence('hao','好','hao3','meaning,pronunciation,hanzi')]);await expect(page.locator('.writingExercise')).toHaveAttribute('data-phase','demo');await expect(page.locator('.lessonCard > .eyebrow')).toContainText('Schreiben lernen');expect((await events(page)).filter(e=>e.type==='attempt')).toHaveLength(0);
 await paperIntroduction(page);await expect(page.locator('.writingExercise')).toHaveAttribute('data-phase','saved');expect((await events(page)).some(e=>e.type==='introduction_dimensions'&&e.detail.dimensions==='writing')).toBe(true);await page.getByRole('button',{name:'Weiter',exact:true}).click();await expect(page.locator('.writingExercise')).toHaveAttribute('data-phase','writing');await expect(page.locator('.writingExercise')).toHaveAttribute('data-scaffold','delayed_recall');
});
test('known word forms in a new phrase skip repeated Hanzi focus, but receive phrase meaning and explicit tone',async({page})=>{
 await plan(page,['meet-nihao'],[evidence('ni','你','ni3','hanzi'),evidence('hao','好','hao3','hanzi')]);await expect(page.locator('.attentionIntroduction')).toHaveAttribute('data-focus','tone');await expect(page.getByRole('button',{name:'Schriftbild ansehen',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Bedeutung dazunehmen',exact:true}).click();await expect(page.locator('.attentionIntroduction')).toHaveAttribute('data-focus','connect');await expect(page.getByText('Bekannte Wörter, neue Verbindung',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'你好 erkunden',exact:true})).toBeVisible();expect((await events(page)).some(e=>e.type==='tone_attention_confirmed')).toBe(true);expect((await events(page)).some(e=>e.type==='introduction_dimensions'&&e.detail.item==='nihao'&&e.detail.dimensions.includes('meaning'))).toBe(false);
 await page.getByRole('button',{name:'Weiter',exact:true}).click();expect((await events(page)).some(e=>e.type==='introduction_dimensions'&&e.detail.item==='nihao'&&e.detail.dimensions.includes('meaning'))).toBe(true);
});
test('skipping blocked audio cannot unlock later listening assessment',async({page})=>{
 await page.addInitScript(()=>{const play=HTMLMediaElement.prototype.play;(window as any).audioBlocked=true;HTMLMediaElement.prototype.play=function(){return (window as any).audioBlocked?Promise.reject(new DOMException('blocked','NotAllowedError')):play.call(this);};});
 await plan(page,['d-meet-qing','d-hear-qing']);await expect(page.locator('.attentionIntroduction')).toHaveAttribute('data-focus','hear');await page.getByRole('button',{name:'Schrift ohne Warten ansehen',exact:true}).click();await page.getByRole('button',{name:'Bedeutung dazunehmen',exact:true}).click();await page.getByRole('button',{name:'Weiter',exact:true}).click();await expect(page.locator('.attentionIntroduction')).toHaveAttribute('data-focus','hear');await expect(page.getByRole('button',{name:'Prüfen',exact:true})).toHaveCount(0);expect((await events(page)).some(e=>e.type==='introduction_dimensions'&&e.detail.dimensions.includes('pronunciation'))).toBe(false);
 await page.getByRole('button',{name:'Schrift ohne Warten ansehen',exact:true}).click();await expect(page.locator('.attentionIntroduction')).toHaveAttribute('data-focus','connect');await page.evaluate(()=>{(window as any).audioBlocked=false;});await page.locator('.referenceAudio .audioButton').first().click();await expect.poll(async()=> (await events(page)).some(e=>e.type==='introduction_dimensions'&&e.detail.dimensions.includes('pronunciation'))).toBe(true);await expect(page.locator('.attentionIntroduction')).toHaveAttribute('data-focus','connect');
});
