const $app = document.querySelector('#app');
const storeKey = 'mandarin-prototype-v01';
const state = Object.assign({script:'traditional',step:0,name:'',completed:false,revisit:0}, JSON.parse(localStorage.getItem(storeKey)||'{}'));
const save=()=>localStorage.setItem(storeKey,JSON.stringify(state));
const h=(t,a={},...c)=>{const e=document.createElement(t);for(const[k,v]of Object.entries(a)){if(k==='class')e.className=v;else if(k.startsWith('on'))e.addEventListener(k.slice(2).toLowerCase(),v);else e.setAttribute(k,v)}for(const x of c)e.append(x?.nodeType?x:document.createTextNode(String(x??'')));return e};
const play=src=>new Audio(src).play();
const cn=(trad,simp)=>state.script==='traditional'?trad:simp;
function btn(label,on,secondary=false){return h('button',{class:secondary?'secondary':'',onclick:on},label)}
function audioBtn(src,label='Listen'){return btn('▶ '+label,()=>play(src),true)}
function frame(content){$app.innerHTML='';const shell=h('div',{class:'shell'}); if(state.started){const head=h('div',{class:'head'},btn('Lesson 1',()=>{state.started=false;save();render()},true),h('div',{class:'track'},h('span',{style:`width:${Math.round(((state.step+1)/steps().length)*100)}%`})),h('span',{class:'count'},`${state.step+1}/${steps().length}`));shell.append(head)}shell.append(h('section',{class:'card'},content));$app.append(shell)}
function start(){const d=h('div',{class:'step'},h('p',{class:'eyebrow'},'Foundation · Lesson 1'),h('div',{class:'hero'},'你好'),h('p',{class:'lead'},'Say hello. Say your name. Hear what tone does.'));const seg=h('div',{class:'seg'});['traditional','simplified'].forEach(s=>seg.append(btn(s[0].toUpperCase()+s.slice(1),()=>{state.script=s;save();render()},false)));[...seg.children].forEach((b,i)=>b.classList.toggle('on',(i===0)===(state.script==='traditional')));d.append(h('div',{},h('p',{},'Characters'),seg),h('p',{class:'muted'},'About 15–20 minutes · local progress · offline after first load.'),btn('Start',()=>{state.started=true;save();render()}));frame(d)}
function next(){const ss=steps();if(state.step>=ss.length-1){state.completed=true;state.started=false;state.step=0;save();return render()}state.step++;save();render()}
function listenFirst(){let fb=h('p',{class:'feedback hidden'});const d=h('div',{class:'step'},h('p',{class:'eyebrow'},'First contact'),h('h2',{},'Just listen.'),audioBtn('audio/mandarin/nihao.wav','Play'),h('p',{},'What is happening?'),h('div',{class:'row'},btn('A greeting',()=>{fb.textContent='Exactly. A greeting.';fb.classList.remove('hidden');cont.classList.remove('hidden')},true),btn('A goodbye',()=>{fb.textContent='It is a greeting. You’ll hear it again in a moment.';fb.classList.remove('hidden');cont.classList.remove('hidden')},true)),fb);const cont=btn('Continue',next);cont.classList.add('hidden');d.append(cont);frame(d)}
function pitchRecorder(target='free'){const wrap=h('div',{class:'panel'});const svg=h('svg',{class:'pitch',viewBox:'0 0 300 100'});const fb=h('p',{class:'feedback hidden'});let stop=null;const b=btn('Record locally',async()=>{if(stop){stop();stop=null;b.textContent='Record locally';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const ctx=new AudioContext();const src=ctx.createMediaStreamSource(stream);const an=ctx.createAnalyser();an.fftSize=2048;src.connect(an);const buf=new Float32Array(an.fftSize),pts=[];let raf,last=0;const start=performance.now();const ac=()=>{let rms=0;for(const x of buf)rms+=x*x;rms=Math.sqrt(rms/buf.length);if(rms<.015)return null;let best=-1,lag=-1;for(let l=Math.floor(ctx.sampleRate/420);l<=Math.min(Math.floor(ctx.sampleRate/70),buf.length-1);l++){let c=0;for(let i=0;i<buf.length-l;i++)c+=buf[i]*buf[i+l];if(c>best){best=c;lag=l}}return lag>0?ctx.sampleRate/lag:null};const tick=t=>{if(t-last>45){an.getFloatTimeDomainData(buf);const hz=ac();if(hz)pts.push({t:(t-start)/1000,hz});last=t}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);b.textContent='Stop';stop=()=>{cancelAnimationFrame(raf);stream.getTracks().forEach(x=>x.stop());ctx.close();drawPitch(svg,pts);fb.textContent=feedback(pts,target);fb.classList.remove('hidden')}}catch{fb.textContent='Microphone unavailable. Continue without automatic pitch feedback.';fb.classList.remove('hidden')}});wrap.append(b,svg,fb,h('p',{class:'privacy'},'Audio is analyzed in this browser and is not uploaded.'));return wrap}
function drawPitch(svg,pts){svg.innerHTML='';if(pts.length<2)return;const hs=pts.map(p=>p.hz),min=Math.min(...hs),max=Math.max(...hs),span=Math.max(1,max-min);const poly=pts.map((p,i)=>`${i/(pts.length-1)*300},${90-(p.hz-min)/span*70}`).join(' ');svg.append(h('polyline',{points:poly,fill:'none',stroke:'currentColor','stroke-width':'4'}))}
function feedback(pts,target){if(pts.length<5)return'I could not detect a stable pitch yet. Try once more.';const f=pts[0].hz,l=pts.at(-1).hz,d=(l-f)/Math.max(f,1);if(target==='rising')return d>.12?'Clear rise.':'The contour stayed fairly flat. Try a more obvious rise.';if(target==='falling')return d<-.12?'Clear fall.':'The fall was not very clear yet.';if(target==='low')return'For tone 3, focus first on getting low; a full dip-and-rise is not always required.';return'Pitch captured. Compare the shape, not the absolute height.'}
function greeting(){frame(h('div',{class:'step center'},h('div',{class:'hanzi'},'你好'),h('p',{class:'pinyin'},'nǐ hǎo'),h('p',{},'hello'),audioBtn('audio/mandarin/nihao.wav'),pitchRecorder('free'),btn('Continue',next)))}
function toneLab(){const ts=[['mā','媽 / 妈','mother','ma1.wav','high'],['má','麻','hemp','ma2.wav','rising'],['mǎ','馬 / 马','horse','ma3.wav','low'],['mà','罵 / 骂','scold','ma4.wav','falling']];let reveal=false;const d=h('div',{class:'step'},h('p',{class:'eyebrow'},'Tone lab'),h('h2',{},'Same syllable. Different word.'),h('p',{},'Listen before you memorize rules.'));const g=h('div',{class:'tonegrid'});for(const [p,z,m,a]of ts){const c=h('div',{class:'tone'},audioBtn('audio/mandarin/'+a,p));c.dataset.extra=`${z}|${m}`;g.append(c)}d.append(g);const r=btn('Reveal meanings',()=>{if(reveal)return;reveal=true;for(const c of g.children){const[z,m]=c.dataset.extra.split('|');c.append(h('strong',{},z),h('span',{},m))}r.remove();d.append(h('p',{class:'feedback'},'Tone is not decoration.'),pitchRecorder('rising'),btn('Continue',next))});d.append(r);frame(d)}
function writingPad(char,onDone){let paper=false,guide=true,strokes=[],cur=null;const wrap=h('div',{class:'panel'});function paint(){if(paper)return;const c=canvas,ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.round(rect.width*dpr);c.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);ctx.strokeStyle='#ddd8ce';ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(rect.width/2,0);ctx.lineTo(rect.width/2,rect.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,rect.height/2);ctx.lineTo(rect.width,rect.height/2);ctx.stroke();ctx.setLineDash([]);if(guide){ctx.fillStyle='rgba(24,24,22,.1)';ctx.font=`${Math.min(rect.width,rect.height)*.7}px serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(char,rect.width/2,rect.height/2)}ctx.strokeStyle='#181816';ctx.lineCap='round';ctx.lineWidth=6;for(const s of strokes){if(s.length<2)continue;ctx.beginPath();ctx.moveTo(s[0].x,s[0].y);for(const p of s.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke()}}const canvas=h('canvas',{class:'writing'});const pos=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);cur=[pos(e)];strokes.push(cur)};canvas.onpointermove=e=>{if(cur){cur.push(pos(e));paint()}};canvas.onpointerup=()=>{cur=null;paint()};const controls=h('div',{class:'row'},btn('Clear',()=>{strokes=[];paint()},true),btn('Hide / show guide',()=>{guide=!guide;paint()},true),btn('Use paper',()=>{paper=true;wrap.classList.add('printable');wrap.innerHTML='';wrap.append(h('div',{class:'paperchar'},char),h('p',{},'Write this character on paper. Then check it yourself.'),h('div',{class:'row'},btn('Print worksheet',()=>print()),btn('Back to screen',()=>{paper=false;renderCurrentWriting()},true)),btn('I checked it',onDone))},true));function renderCurrentWriting(){wrap.classList.remove('printable');wrap.innerHTML='';wrap.append(canvas,controls,btn('Done',onDone));requestAnimationFrame(paint)}renderCurrentWriting();return wrap}
function writeStep(char,pinyin,meaning,audio){frame(h('div',{class:'step'},h('div',{class:'center'},h('div',{class:'hanzi'},char),h('p',{class:'pinyin'},pinyin),h('p',{},meaning),audioBtn(audio)),writingPad(char,next)))}
function compose(){frame(h('div',{class:'step center'},h('div',{class:'sentence'},'你 + 好 → 你好'),h('p',{class:'pinyin'},'nǐ hǎo'),audioBtn('audio/mandarin/nihao.wav'),h('p',{class:'feedback'},'You already know both characters.'),btn('Continue',next)))}
function nameIntro(){const d=h('div',{class:'step'},h('p',{class:'eyebrow'},'Make it yours'),h('h2',{class:'sentence'},'我叫 …'),h('p',{},'叫 jiào is used here for “to be called”.'),audioBtn('audio/mandarin/wojiao.wav','Hear 我叫'));const inp=h('input',{class:'nameinput',placeholder:'Your name',value:state.name});inp.addEventListener('input',()=>{state.name=inp.value;save();sent.textContent='我叫 '+(state.name||'…')+'。'});const sent=h('p',{class:'sentence'},'我叫 '+(state.name||'…')+'。');d.append(inp,sent,pitchRecorder('free'),btn('Continue',next));frame(d)}
function nameQuestion(){frame(h('div',{class:'step'},h('p',{class:'eyebrow'},'A real question'),audioBtn('audio/mandarin/nijiaoshenmemingzi.wav','Listen first'),h('h2',{class:'sentence'},cn('你叫什麼名字？','你叫什么名字？')),h('p',{class:'pinyin'},'nǐ jiào shénme míngzi?'),h('p',{},'Chinese often leaves the question word where the answer would go.'),h('div',{class:'feedback'},'我叫 '+(state.name||'…')+'。'),pitchRecorder('free'),btn('Continue',next)))}
function phrase(trad,simp,pinyin,meaning,audio){frame(h('div',{class:'step center'},h('div',{class:'hanzi'},cn(trad,simp)),h('p',{class:'pinyin'},pinyin),h('p',{},meaning),audioBtn(audio),pitchRecorder('free'),btn('Continue',next)))}
function dialogue(){frame(h('div',{class:'step'},h('p',{class:'eyebrow'},'Mini interaction'),h('h2',{},'No subtitles first.'),h('div',{class:'panel'},audioBtn('audio/mandarin/nihao.wav','1 · Someone greets you'),h('p',{},'Your answer: 你好。'),audioBtn('audio/mandarin/nijiaoshenmemingzi.wav','2 · A question'),h('p',{},'Your answer: 我叫 '+(state.name||'…')+'。'),audioBtn('audio/mandarin/xiexie.wav','3 · They thank you'),audioBtn('audio/mandarin/zaijian.wav','4 · They leave')),btn('I did it',next)))}
function recall(){frame(h('div',{class:'step'},h('p',{class:'eyebrow'},'Honest recall'),h('h2',{},'No Pinyin.'),h('p',{},'Write 好 from memory — on screen or on paper.'),writingPad('好',next)))}
function outro(){frame(h('div',{class:'step center'},h('div',{class:'quote'},'千里之行，始於足下。'),h('p',{},'A journey of a thousand miles begins with the first step.'),h('p',{class:'muted'},'Laozi, chapter 64'),btn('Finish',next)))}
const base=[listenFirst,greeting,toneLab,()=>writeStep('我','wǒ','I / me','audio/mandarin/wo.wav'),()=>writeStep('你','nǐ','you','audio/mandarin/ni.wav'),()=>writeStep('好','hǎo','good','audio/mandarin/hao.wav'),compose,nameIntro,nameQuestion,()=>phrase('謝謝','谢谢','xièxie','thank you','audio/mandarin/xiexie.wav'),()=>phrase('再見','再见','zàijiàn','goodbye','audio/mandarin/zaijian.wav'),dialogue,recall,outro];
function steps(){if(!state.revisit)return base;return [greeting,recall,toneLab,compose,nameQuestion,dialogue,()=>phrase('謝謝','谢谢','xièxie','thank you','audio/mandarin/xiexie.wav'),()=>phrase('再見','再见','zàijiàn','goodbye','audio/mandarin/zaijian.wav'),outro]}
function render(){if(state.completed){frame(h('div',{class:'step center'},h('p',{class:'eyebrow'},'Lesson complete'),h('div',{class:'hero'},'你好。'),h('p',{class:'lead'},'You can greet someone, say your name and recognize 我 · 你 · 好.'),h('p',{},'Progress is stored locally in this browser.'),btn('Do it again — differently',()=>{state.completed=false;state.started=true;state.revisit++;state.step=0;save();render()})));return}if(!state.started)return start();const ss=steps();if(state.step>=ss.length){state.completed=true;state.started=false;state.step=0;save();return render()}ss[state.step]()}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
